apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "celery.fullname" . }}
  labels:
    {{- include "celery.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "celery.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "celery.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: celery
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          command: ["celery", "-A", "llm_benchmark", "worker", "--loglevel=info"]
          livenessProbe:
            exec:
              command: ["pgrep", "celery"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["pgrep", "celery"]
            initialDelaySeconds: 30
            periodSeconds: 10
