replicaCount: 3

image:
  repository: your-dockerhub/llm-benchmark-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: api.yourdomain.com
      paths:
        - /

env:
  - name: DATABASE_URL
    value: "postgresql://postgres:password@postgresql:5432/llm_benchmark"
  - name: REDIS_URL
    value: "redis://redis:6379/1"
  - name: CELERY_BROKER_URL
    value: "redis://redis:6379/0"
  - name: CELERY_RESULT_BACKEND
    value: "redis://redis:6379/0"
  - name: SECRET_KEY
    value: "your-secret-key"
