replicaCount: 2

image:
  repository: your-dockerhub/llm-benchmark-celery
  tag: latest
  pullPolicy: IfNotPresent

env:
  - name: DATABASE_URL
    value: "postgresql://postgres:password@postgresql:5432/llm_benchmark"
  - name: REDIS_URL
    value: "redis://redis:6379/1"
  - name: CELERY_BROKER_URL
    value: "redis://redis:6379/0"
  - name: CELERY_RESULT_BACKEND
    value: "redis://redis:6379/0"
  - name: SECRET_KEY
    value: "your-secret-key"
